---
version: "2.1"
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/home-media/sabnzbd:/config
      - /mnt/Downloads/Usenet/complete:/downloads
      - /mnt/Downloads/Usenet/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
    volumes:
      - /etc/home-media/radarr:/config
      - /mnt/Media/Videos/Movies:/media
      - /mnt/Downloads/Usenet/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
    volumes:
      - /etc/home-media/sonarr:/config
      - /mnt/Media/Videos/Series:/media
      - /mnt/Downloads/Usenet/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /etc/home-media/plex:/config
      - /mnt/Media/Videos/Series:/tv
      - /mnt/Media/Videos/Movies:/movies
    restart: unless-stopped
